version: '3'

services:
  payara:
    image: payara/micro:latest
    environment:
      - TZ=Asia/Bangkok
      - JDBC_URL=jdbc\:h2\:mem\:testdb
      - JDBC_USER=testuser
      - JDBC_PASSWORD=testuser
      - JDBC_DATASOURCE_CLASSNAME=org.h2.jdbcx.JdbcDataSource
      - JDBC_JNDI_NAME=jdbc/testdb
      - JDBC_POOL_NAME=test-db-pool
      - JDBC_POOL_MIN=1
      - JDBC_POOL_MAX=10
      - JDBC_VALIDATION_CLASSNAME=org.glassfish.api.jdbc.validation.H2ConnectionValidation
    volumes:
      - ./boot-scripts:/opt/payara/resources/boot-scripts
    command:
      - --prebootcommandfile
      - '/opt/payara/resources/boot-scripts/pre-boot.txt'
      - --postbootcommandfile
      - '/opt/payara/resources/boot-scripts/post-boot.txt'
